version: "3"

services:
  mysql:
    image: mysql:5.6.34
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=

  app:
    build:
      context: .
    command: bundle exec puma --config config/puma.rb
    environment:
      RAILS_ENV: development
    volumes:
      - ".:/app"
    depends_on:
      - "mysql"

  client:
    build:
      context: ./client
    command: npm run build
    volumes:
      - ./client/:/app
      - web:/app/build
      - node_modules:/app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - '3000:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - web:/var/www/html
    depends_on:
      - 'app'
      - 'client'

volumes:
  dbdata:
  node_modules:
  web:
